### ISSUE TITLE
Specify minimum required Python version

### ISSUE THREAD

**Issue by jtomori** [martinResearch/openexr_numpy#3]
Hello,
thank you for sharing this module.

It might be worth specifying the minimum required Python version. [Your](https://github.com/martinResearch/openexr_numpy/blob/f4475cba1c9eacbe98fa2bb034b1fe24f234b540/openexr_numpy/openexr_numpy.py#L3) use of [`typing.Literal`](https://docs.python.org/3/library/typing.html#typing.Literal) requires Python 3.8 or newer. This could be [specified](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#python-requirement) with `python_requires=">=3.8"` in the [`setup()`](https://github.com/martinResearch/openexr_numpy/blob/f4475cba1c9eacbe98fa2bb034b1fe24f234b540/setup.py#L21) call in `setup.py`.

Best,
Juraj

**Comment by martinResearch** [comment]
I added the line in the setup.py. Thank you for the suggestion!
